move git config after chown

diff --git a/.github/workflows/melodic.yml b/.github/workflows/melodic.yml
--- a/.github/workflows/melodic.yml
+++ b/.github/workflows/melodic.yml
@@ -20,10 +20,10 @@ jobs:
         run: |
           set -x
           export USER=$(whoami)
-          git config --global --add safe.directory $GITHUB_WORKSPACE || echo "OK" # Show 'could not lock config file /github/home/.gitconfig: Permission denied', but it is ok
           sudo mkdir -p /__w/
           sudo chmod 777 -R /__w/
           sudo chown -R $USER $HOME
+          git config --global --add safe.directory $GITHUB_WORKSPACE || echo "OK" # Show 'could not lock config file /github/home/.gitconfig: Permission denied', but it is ok
       - name: Checkout
         uses: actions/checkout@v2
       - name: Run jsk_travis
